import type { Recipe } from './types';
import { recipeSchema } from './validation';

// First-party curated recipes (blueprint §5) — Phase 4 has no live recipe-API
// integration yet (that's Phase 6's RecipeDataProvider). Ingredients link to
// real catalog products via productId where a sensible match exists, so
// ingredient-matching against the cart works on real data. Tags like
// high_protein/low_calorie are qualitative editorial categorisation, not
// numeric nutrition claims — recipe detail pages state plainly that per-
// serving nutrition data isn't available yet, same honesty rule as products.
const rawRecipes: Recipe[] = [
  {
    id: 'overnight-oats-banana',
    title: 'Overnight Oats with Banana',
    course: 'breakfast',
    tags: ['vegetarian', 'no_cook', 'budget', 'student'],
    method: [],
    source: 'curated',
    totalMinutes: 5,
    servings: 1,
    ingredients: [
      { name: 'Rolled oats', quantity: 50, unit: 'g', productId: 'prod-coles-rolled-oats' },
      { name: 'Full cream milk', quantity: 150, unit: 'mL', productId: 'prod-coles-full-cream-milk' },
      { name: 'Banana, sliced', quantity: 1, unit: 'each', productId: 'prod-coles-bananas-per-kg' },
      { name: 'Honey', quantity: 1, unit: 'tbsp', pantryStaple: true },
    ],
    instructions: [
      'Combine oats and milk in a jar or container.',
      'Stir in honey, cover, and refrigerate overnight.',
      'Top with sliced banana before eating.',
    ],
    allergens: ['dairy'],
    costPerServingAud: 1.0,
    storageNotes: 'Keeps refrigerated for up to 3 days.',
  },
  {
    id: 'greek-yoghurt-berry-bowl',
    title: 'Greek Yoghurt & Berry Bowl',
    course: 'breakfast',
    tags: ['vegetarian', 'gluten_free', 'high_protein'],
    method: ['quick'],
    source: 'curated',
    totalMinutes: 5,
    servings: 1,
    ingredients: [
      {
        name: 'Greek style natural yoghurt',
        quantity: 200,
        unit: 'g',
        productId: 'prod-woolworths-greek-style-natural-yoghurt',
      },
      { name: 'Frozen berries', quantity: 50, unit: 'g', productId: 'prod-coles-frozen-berries' },
      { name: 'Honey', quantity: 1, unit: 'tsp', pantryStaple: true },
    ],
    instructions: [
      'Spoon yoghurt into a bowl.',
      'Top with frozen berries (thawed) and a drizzle of honey.',
    ],
    allergens: ['dairy'],
    costPerServingAud: 2.0,
  },
  {
    id: 'chicken-rice-stir-fry',
    title: 'Chicken & Rice Stir-Fry',
    course: 'main',
    tags: ['gluten_free', 'high_protein', 'family'],
    method: ['one_pot', 'quick'],
    source: 'curated',
    totalMinutes: 25,
    servings: 4,
    ingredients: [
      {
        name: 'Chicken breast fillets, diced',
        quantity: 500,
        unit: 'g',
        productId: 'prod-coles-chicken-breast-fillets',
      },
      { name: 'Basmati rice', quantity: 300, unit: 'g', productId: 'prod-coles-basmati-rice' },
      {
        name: 'Frozen mixed vegetables',
        quantity: 300,
        unit: 'g',
        productId: 'prod-coles-frozen-mixed-vegetables',
      },
      { name: 'Garlic, minced', quantity: 2, unit: 'cloves', pantryStaple: true },
      { name: 'Oil', quantity: 1, unit: 'tbsp', pantryStaple: true },
    ],
    instructions: [
      'Cook rice according to packet instructions.',
      'Heat oil in a large pan, cook garlic and chicken until browned through.',
      'Add frozen vegetables, cook until tender.',
      'Serve chicken and vegetables over rice.',
    ],
    allergens: [],
    costPerServingAud: 2.75,
  },
  {
    id: 'beef-mince-tomato-pasta',
    title: 'Beef Mince & Tomato Pasta',
    course: 'main',
    tags: ['family', 'budget'],
    method: ['one_pot'],
    source: 'curated',
    totalMinutes: 30,
    servings: 4,
    ingredients: [
      { name: 'Beef mince', quantity: 500, unit: 'g', productId: 'prod-iga-beef-mince-5-star' },
      { name: 'Spaghetti pasta', quantity: 500, unit: 'g', productId: 'prod-woolworths-spaghetti-pasta' },
      {
        name: 'Roma tomatoes, diced',
        quantity: 500,
        unit: 'g',
        productId: 'prod-woolworths-roma-tomatoes-per-kg',
      },
      { name: 'Onion, diced', quantity: 1, unit: 'each', pantryStaple: true },
    ],
    instructions: [
      'Cook pasta according to packet instructions.',
      'Brown beef mince and onion in a large pan.',
      'Add tomatoes, simmer 15 minutes until sauce thickens.',
      'Serve sauce over pasta.',
    ],
    allergens: ['gluten'],
    costPerServingAud: 2.95,
  },
  {
    id: 'tofu-chickpea-curry',
    title: 'Tofu & Chickpea Curry',
    course: 'main',
    tags: ['vegan', 'vegetarian', 'gluten_free', 'dairy_free', 'budget'],
    method: ['one_pot'],
    source: 'curated',
    totalMinutes: 30,
    servings: 4,
    ingredients: [
      { name: 'Extra firm tofu, cubed', quantity: 300, unit: 'g', productId: 'prod-coles-extra-firm-tofu' },
      { name: 'Canned chickpeas', quantity: 400, unit: 'g', productId: 'prod-coles-canned-chickpeas' },
      { name: 'Frozen peas', quantity: 200, unit: 'g', productId: 'prod-woolworths-frozen-peas' },
      { name: 'Curry paste', quantity: 2, unit: 'tbsp', pantryStaple: true },
    ],
    instructions: [
      'Pan-fry tofu until golden, set aside.',
      'Cook curry paste briefly, add chickpeas and a splash of water, simmer 10 minutes.',
      'Stir in peas and tofu, cook 5 more minutes.',
    ],
    allergens: ['soy'],
    costPerServingAud: 1.55,
  },
  {
    id: 'air-fryer-chicken-potato',
    title: 'Air-Fryer Chicken & Potato',
    course: 'main',
    tags: ['gluten_free', 'family'],
    method: ['air_fryer'],
    source: 'curated',
    totalMinutes: 35,
    servings: 4,
    ingredients: [
      {
        name: 'Chicken breast fillets',
        quantity: 500,
        unit: 'g',
        productId: 'prod-coles-chicken-breast-fillets',
      },
      {
        name: 'Brushed potatoes, chopped',
        quantity: 600,
        unit: 'g',
        productId: 'prod-iga-brushed-potatoes-per-kg',
      },
      { name: 'Oil', quantity: 1, unit: 'tbsp', pantryStaple: true },
      { name: 'Salt & pepper', quantity: 1, unit: 'pinch', pantryStaple: true },
    ],
    instructions: [
      'Toss chicken and potato pieces in oil, salt, and pepper.',
      'Air-fry at 200°C for 20 minutes, turning halfway.',
      'Check chicken is cooked through before serving.',
    ],
    allergens: [],
    costPerServingAud: 2.65,
  },
  {
    id: 'bbq-chicken-veg',
    title: 'BBQ Chicken & Veg',
    course: 'main',
    tags: ['gluten_free', 'family'],
    method: ['bbq'],
    source: 'curated',
    totalMinutes: 25,
    servings: 4,
    ingredients: [
      {
        name: 'Chicken breast fillets',
        quantity: 500,
        unit: 'g',
        productId: 'prod-coles-chicken-breast-fillets',
      },
      {
        name: 'Frozen mixed vegetables',
        quantity: 300,
        unit: 'g',
        productId: 'prod-coles-frozen-mixed-vegetables',
      },
    ],
    instructions: [
      'Grill chicken on the BBQ until cooked through, ~7 minutes per side.',
      'Steam or grill vegetables alongside.',
      'Rest chicken 5 minutes before slicing.',
    ],
    allergens: [],
    costPerServingAud: 2.45,
  },
  {
    id: 'hummus-veggie-snack-plate',
    title: 'Hummus & Rice Cake Snack Plate',
    course: 'snack',
    tags: ['vegan', 'vegetarian', 'gluten_free', 'no_cook'],
    method: ['quick'],
    source: 'curated',
    totalMinutes: 5,
    servings: 2,
    ingredients: [
      { name: 'Hummus dip', quantity: 200, unit: 'g', productId: 'prod-coles-hummus-dip' },
      { name: 'Rice cakes', quantity: 130, unit: 'g', productId: 'prod-coles-rice-cakes' },
    ],
    instructions: ['Serve hummus alongside rice cakes for dipping.'],
    allergens: [],
    costPerServingAud: 2.9,
  },
  {
    id: 'trail-mix-energy-bites',
    title: 'Trail Mix Energy Bites',
    course: 'snack',
    tags: ['vegetarian', 'budget'],
    method: [],
    source: 'curated',
    totalMinutes: 10,
    servings: 6,
    ingredients: [
      { name: 'Trail mix', quantity: 300, unit: 'g', productId: 'prod-woolworths-trail-mix' },
      {
        name: 'Peanut butter smooth',
        quantity: 100,
        unit: 'g',
        productId: 'prod-woolworths-peanut-butter-smooth',
      },
    ],
    instructions: [
      'Pulse trail mix in a food processor until roughly chopped.',
      'Mix in peanut butter until it binds together.',
      'Roll into balls and refrigerate 30 minutes.',
    ],
    allergens: ['tree nut', 'peanut'],
    costPerServingAud: 1.2,
    storageNotes: 'Keeps refrigerated for up to a week.',
  },
  {
    id: 'chocolate-yoghurt-dessert-pot',
    title: 'Chocolate & Yoghurt Dessert Pot',
    course: 'dessert',
    tags: ['vegetarian'],
    method: ['quick'],
    source: 'curated',
    totalMinutes: 10,
    servings: 4,
    ingredients: [
      { name: 'Chocolate block, melted', quantity: 90, unit: 'g', productId: 'prod-coles-chocolate-block' },
      {
        name: 'Vanilla yoghurt tub',
        quantity: 500,
        unit: 'g',
        productId: 'prod-coles-vanilla-yoghurt-tub',
      },
    ],
    instructions: [
      'Melt chocolate in short bursts in the microwave, stirring between each.',
      'Swirl melted chocolate through yoghurt in serving cups.',
      'Chill 10 minutes before serving.',
    ],
    allergens: ['dairy'],
    costPerServingAud: 1.4,
  },
  {
    id: 'frozen-berry-custard-cups',
    title: 'Frozen Berry & Custard Cups',
    course: 'dessert',
    tags: ['vegetarian', 'gluten_free'],
    method: ['quick'],
    source: 'curated',
    totalMinutes: 10,
    servings: 4,
    ingredients: [
      { name: 'Frozen berries', quantity: 250, unit: 'g', productId: 'prod-coles-frozen-berries' },
      { name: 'Custard tub', quantity: 300, unit: 'g', productId: 'prod-woolworths-custard-tub' },
    ],
    instructions: [
      'Layer thawed berries and custard in serving cups.',
      'Chill 10 minutes before serving.',
    ],
    allergens: ['dairy'],
    costPerServingAud: 1.3,
  },
  {
    id: 'green-tea-orange-refresher',
    title: 'Green Tea & Orange Refresher',
    course: 'drink',
    tags: ['vegan', 'vegetarian', 'low_calorie'],
    method: ['quick'],
    source: 'curated',
    totalMinutes: 5,
    servings: 2,
    ingredients: [
      { name: 'Green tea bags', quantity: 2, unit: 'each', productId: 'prod-coles-green-tea-bags' },
      { name: 'Orange juice', quantity: 200, unit: 'mL', productId: 'prod-coles-orange-juice' },
      { name: 'Ice', quantity: 1, unit: 'cup', pantryStaple: true },
    ],
    instructions: [
      'Brew green tea, let cool.',
      'Combine with orange juice and ice, stir and serve.',
    ],
    allergens: [],
    costPerServingAud: 0.4,
  },
  {
    id: 'post-workout-protein-shake',
    title: 'Post-Workout Protein Shake',
    course: 'drink',
    tags: ['vegetarian', 'high_protein', 'gluten_free'],
    method: ['quick'],
    source: 'curated',
    totalMinutes: 3,
    servings: 1,
    ingredients: [
      {
        name: 'Whey protein powder',
        quantity: 30,
        unit: 'g',
        productId: 'prod-woolworths-whey-protein-powder',
      },
      { name: 'Full cream milk', quantity: 300, unit: 'mL', productId: 'prod-coles-full-cream-milk' },
      { name: 'Banana', quantity: 1, unit: 'each', productId: 'prod-coles-bananas-per-kg' },
    ],
    instructions: ['Blend all ingredients until smooth.'],
    allergens: ['dairy'],
    costPerServingAud: 2.35,
  },
  {
    id: 'budget-noodle-egg-meal-prep',
    title: 'Budget Noodle & Egg Meal-Prep',
    course: 'meal_prep',
    tags: ['budget', 'student'],
    method: ['one_pot', 'quick'],
    source: 'curated',
    totalMinutes: 15,
    servings: 2,
    ingredients: [
      {
        name: '2 Minute noodles',
        quantity: 2,
        unit: 'packs',
        productId: 'prod-coles-2-minute-noodles-5pk',
      },
      { name: 'Free range eggs', quantity: 2, unit: 'each', productId: 'prod-coles-free-range-eggs-12pk' },
      { name: 'Frozen peas', quantity: 100, unit: 'g', productId: 'prod-woolworths-frozen-peas' },
    ],
    instructions: [
      'Cook noodles according to packet instructions, reserve seasoning.',
      'Soft-boil or fry eggs.',
      'Stir peas through hot noodles, top with egg.',
      'Divide into containers for the week.',
    ],
    allergens: ['gluten'],
    costPerServingAud: 1.65,
    storageNotes: 'Best eaten fresh; noodles soften on reheating.',
  },
  {
    id: 'baked-beans-on-toast',
    title: 'Baked Beans on Toast',
    course: 'breakfast',
    tags: ['vegetarian', 'budget', 'student'],
    method: ['quick'],
    source: 'curated',
    totalMinutes: 10,
    servings: 2,
    ingredients: [
      { name: 'Canned baked beans', quantity: 420, unit: 'g', productId: 'prod-coles-canned-baked-beans' },
      {
        name: 'Home brand white bread',
        quantity: 4,
        unit: 'slices',
        productId: 'prod-iga-home-brand-white-bread',
      },
    ],
    instructions: ['Toast bread.', 'Heat beans in a saucepan or microwave.', 'Serve beans over toast.'],
    allergens: ['gluten'],
    costPerServingAud: 1.1,
  },
  {
    id: 'keto-egg-spinach-scramble',
    title: 'Keto Egg & Spinach Scramble',
    course: 'breakfast',
    tags: ['keto', 'gluten_free', 'vegetarian'],
    method: ['quick'],
    source: 'curated',
    totalMinutes: 10,
    servings: 2,
    ingredients: [
      { name: 'Free range eggs', quantity: 4, unit: 'each', productId: 'prod-coles-free-range-eggs-12pk' },
      { name: 'Baby spinach', quantity: 60, unit: 'g', productId: 'prod-coles-baby-spinach' },
      { name: 'Salted butter', quantity: 20, unit: 'g', productId: 'prod-iga-salted-butter' },
    ],
    instructions: [
      'Melt butter in a pan over medium heat.',
      'Wilt spinach briefly, then add beaten eggs.',
      'Scramble gently until just set.',
    ],
    allergens: ['dairy'],
    costPerServingAud: 2.35,
  },
];

export const RECIPES: Recipe[] = rawRecipes.map((r) => recipeSchema.parse(r));

export function getRecipeById(id: string): Recipe | undefined {
  return RECIPES.find((r) => r.id === id);
}
